import { LegalLayout, LegalSection } from '../components/LegalLayout';

export default function Terms() {
  return (
    <LegalLayout title="Terms of Use" updated="June 13, 2026">
      <p className="leading-relaxed text-text-muted">
        These Terms of Use (“Terms”) govern your access to and use of ScriptDrop
        (the “Service”). Please read them carefully. By creating an account or
        using the Service, you agree to these Terms.
      </p>

      <LegalSection heading="1. Acceptance of terms">
        <p>
          By accessing or using ScriptDrop, you agree to be bound by these Terms
          and our Privacy Policy. If you do not agree, do not use the Service. If
          you are using ScriptDrop on behalf of an organization, you represent
          that you have authority to bind that organization to these Terms.
        </p>
      </LegalSection>

      <LegalSection heading="2. User accounts and responsibility">
        <p>
          You are responsible for the activity that happens under your account
          and for keeping your password secure. You must provide accurate
          information when registering and must be at least 18 years old (or the
          age of majority in your jurisdiction) to use the Service. Notify us
          promptly of any unauthorized use of your account.
        </p>
      </LegalSection>

      <LegalSection heading="3. Credits, payments, and refunds">
        <p>
          ScriptDrop sells credits in one-time packs. Each generation consumes
          one credit and produces three scripts. New accounts receive a small
          number of free credits to try the Service.
        </p>
        <p>
          Credits do not expire. Credits have no cash value and are
          non-transferable. Used credits are non-refundable. Unused credits may
          be refunded upon request within seven (7) days of purchase. To request
          a refund of unused credits, contact us using the details below.
        </p>
      </LegalSection>

      <LegalSection heading="4. Acceptable use">
        <p>You agree not to use the Service to:</p>
        <ul className="list-disc space-y-1 pl-6">
          <li>generate spam, deceptive, or fraudulent content;</li>
          <li>create content that is illegal, harassing, hateful, or infringing;</li>
          <li>impersonate others or misrepresent your affiliation;</li>
          <li>
            attempt to reverse engineer, overload, or circumvent the Service’s
            security or rate limits.
          </li>
        </ul>
        <p>
          We may suspend or terminate accounts that violate these rules, without
          refund of used credits.
        </p>
      </LegalSection>

      <LegalSection heading="5. AI-generated content disclaimer">
        <p>
          Scripts are generated by an AI model and are provided “as is.” They may
          contain inaccuracies, claims, or phrasing that are not suitable for
          your use. You are solely responsible for reviewing, editing, and
          verifying any script before publishing or relying on it, including
          ensuring compliance with advertising rules and platform policies.
        </p>
      </LegalSection>

      <LegalSection heading="6. Intellectual property">
        <p>
          As between you and ScriptDrop, you own the scripts you generate and may
          use them for personal or commercial purposes. ScriptDrop retains all
          rights in the Service itself, including its software, design, and
          branding. You may not copy or resell the Service.
        </p>
      </LegalSection>

      <LegalSection heading="7. Limitation of liability">
        <p>
          To the maximum extent permitted by law, ScriptDrop and its suppliers
          will not be liable for any indirect, incidental, special, or
          consequential damages, or for lost profits or revenues, arising out of
          your use of the Service. Our total liability for any claim relating to
          the Service will not exceed the amount you paid us in the twelve months
          before the claim.
        </p>
      </LegalSection>

      <LegalSection heading="8. Governing law">
        <p>
          These Terms are governed by the laws of the State of Delaware, USA,
          without regard to its conflict-of-laws principles. Any disputes will be
          resolved in the state or federal courts located in Delaware.
        </p>
      </LegalSection>

      <LegalSection heading="9. Changes to these terms">
        <p>
          We may update these Terms from time to time. If we make material
          changes, we will update the “Last updated” date above and, where
          appropriate, notify you. Continued use of the Service after changes
          take effect constitutes acceptance.
        </p>
      </LegalSection>

      <LegalSection heading="10. Contact">
        <p>
          Questions about these Terms? Contact us at{' '}
          <span className="text-text-primary">support@scriptdrop.example</span>.
        </p>
      </LegalSection>
    </LegalLayout>
  );
}
